#!/bin/bash
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl enable  wsl-vhd-mount.service >/dev/null 2>&1 || true
    systemctl restart wsl-vhd-mount.service >/dev/null 2>&1 || true
fi

exit 0
