#!/bin/bash
set -e

if command -v systemctl >/dev/null 2>&1; then
    systemctl stop    wsl-vhd-mount.service >/dev/null 2>&1 || true
    systemctl disable wsl-vhd-mount.service >/dev/null 2>&1 || true
    systemctl daemon-reload
fi

exit 0
